image: trion/ng-cli

stages:
  - build
  - test

.build:
  stage: build
  tags:
    - sih_public_runner
  script:
    - echo "installation and build in progress"
    - npm install
    - npm run build.${BUILD_ENVIRONMENT}
  variables:
    BUILD_ENVIRONMENT: aot

build_auto:
  extends: .build
  only:
    - develop
  except:
    - schedules

schedule_build:
  extends: .build
  only:
    - schedules

build_registry:
    extends: .build
    after_script:
      - echo "Deploy artefact in progress"
      - APP_VERSION=$(node -e "console.log(require('./package.json').version)")
      - cd ${CI_PROJECT_DIR}/www
      - zip -q -r ${ZIP_FILE} .
      - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${ZIP_FILE} "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${APP_VERSION}/${CI_PROJECT_NAME}.zip"'
    variables:
      ZIP_FILE: ${CI_PROJECT_DIR}/www/${CI_PROJECT_NAME}.zip
      BUILD_ENVIRONMENT: prod
    artifacts:
      paths:
        - www/*.zip
    only:
        - develop
    when: manual
